version: '3.7'

services:
  server:
    build:
      context: ./short-video-backend
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    ports:
      - "5000:5000"
    depends_on:
      - shortvideomernapp
    networks:
      - app-network
  shortvideomernapp:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./short-video-frontend
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
